// AUTHORIZATION
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

// TOGGLE
export const OPTIONS_BOOL = 'OPTIONS_BOOL';
export const DISPLAY_MODAL_ON = 'DISPLAY_MODAL_ON';
export const DISPLAY_MODAL_OFF = 'DISPLAY_MODAL_OFF';

// ACCOUNT BALANCE
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';
export const ADD_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const ADD_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';
export const TOGGLE_OUTGOINGS = 'TOGGLE_OUTGOINGS';
export const TOGGLE_ACCOUNTS = 'TOGGLE_ACCOUNTS';
export const TOGGLE_TRANSFERS = 'TOGGLE_TRANSFERS';
export const TOGGLE_INCOME = 'TOGGLE_INCOME';
