// AUTHORIZATION
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// TOGGLE
export const OPTIONS_BOOL = 'OPTIONS_BOOL';
export const DISPLAY_MODAL_ON = 'DISPLAY_MODAL_ON';
export const DISPLAY_MODAL_OFF = 'DISPLAY_MODAL_OFF';
export const TOGGLE_OUTGOINGS = 'TOGGLE_OUTGOINGS';
export const TOGGLE_ACCOUNTS = 'TOGGLE_ACCOUNTS';
export const TOGGLE_TRANSFERS = 'TOGGLE_TRANSFERS';
export const TOGGLE_INCOME = 'TOGGLE_INCOME';

// ACCOUNT BALANCE
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';
export const ADD_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const ADD_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';
export const GET_ACCOUNTS_LIST_SUCCESS = 'GET_ACCOUNTS_LIST_SUCCESS';
export const GET_ACCOUNTS_LIST_FAIL = 'GET_ACCOUNTS_LIST_FAIL';

// OUTGOINGS
export const GET_OUTGOINGS_LIST = 'GET_OUTGOINGS_LIST';
export const FAILURE_ADD_OUTGOING_RECORD = 'FAILURE_ADD_OUTGOING_RECORD';
export const FAILURE_DELETE_OUTGOING_RECORD = 'FAILURE_DELETE_OUTGOING_RECORD';

// INCOMES
export const GET_INCOMES_LIST = 'GET_INCOMES_LIST';
export const FAILURE_ADD_INCOME_RECORD = 'FAILURE_ADD_INCOME_RECORD';
export const FAILURE_DELETE_INCOME_RECORD = 'FAILURE_DELETE_INCOME_RECORD';

// TRANSFERS
export const GET_TRANSFERS_LIST = 'GET_TRANSFERS_LIST';
export const FAILURE_ADD_TRANSFER_RECORD = 'FAILURE_ADD_TRANSFER_RECORD';
export const FAILURE_DELETE_TRANSFER_RECORD = 'FAILURE_DELETE_TRANSFER_RECORD';
